spring.application.name=leak-detection-system
spring.datasource.url=jdbc:postgresql://localhost:5432/pipeline_db
spring.datasource.username=pipeline_user
spring.datasource.password=pipeline_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true